AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'GitHub Traffic Tracker - Lambda function to track GitHub repository traffic metrics'

Parameters:
  GitHubRepositories:
    Type: String
    Description: 'Semicolon (;) separated list of GitHub repositories to track (format: owner/repo)'
    Default: 'owner1/repo1;owner2/repo2'
  LambdaTimeout:
    Type: Number
    Description: 'Timeout for Lambda function in seconds'
    Default: 300
    MinValue: 30
    MaxValue: 900
  LambdaMemory:
    Type: Number
    Description: 'Memory allocation for Lambda function in MB'
    Default: 128
    MinValue: 128
    MaxValue: 10240
  LogRetentionDays:
    Type: Number
    Description: 'Number of days to retain CloudWatch logs'
    Default: 1827
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

Resources:
  GitHubTrafficTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GitHubTrafficTracker
      CodeUri: src/function/
      Handler: index.lambda_handler
      Runtime: python3.9
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemory
      Environment:
        Variables:
          LOG_LEVEL: INFO
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: 
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/GitHubTrafficTracker:*
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:github-traffic-tracker:*
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:GitHubTrafficAccessTokens-*
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/GitHubTrafficRepos
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Name: GitHubTrafficTrackerSchedule
            Description: Daily schedule for GitHub Traffic Tracker
            Enabled: true

  GitHubTrafficReposParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 'GitHubTrafficRepos'
      Type: 'String'
      Value: !Ref GitHubRepositories
      Description: 'Semicolon separated list of GitHub repositories to track'

  GitHubTrafficDataLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: github-traffic-tracker
      RetentionInDays: !Ref LogRetentionDays

Outputs:
  GitHubTrafficTrackerFunction:
    Description: GitHub Traffic Tracker Lambda Function ARN
    Value: !GetAtt GitHubTrafficTrackerFunction.Arn
  GitHubTrafficTrackerFunctionIamRole:
    Description: Implicit IAM Role created for GitHub Traffic Tracker function
    Value: !GetAtt GitHubTrafficTrackerFunctionRole.Arn
